<?phpsession_start();if(!isset($_SESSION['logged'])) {	header("Location: index.php");	exit;}require_once('dump.php');$dumps = new Dump();?><!DOCTYPE HTML>
<html>
<head>
	<meta charset="UTF-8">
	<title>Amministrazione</title>	<style>		#button_div > div { float:left; }		table, table td, table th { border:1px solid black; }		.hidden-row { display:none; }		table { border-collapse:collapse; }		th, td { padding:10px; }		.dump_content { width:100%; max-width:1000px; height:100%; max-height:500px; overflow: scroll; }		.center { text-align:center; }		#customQueryDiv { display:none; margin-bottom:10px; }		#customQueryArea { width:500px; height:200px; }		.filename_wrapper a		{			text-decoration:none;			color:inherit;			border-bottom: 1px dashed black;			cursor:pointer;		}		a.delete		{			display:inline-block;			width:20px;			height:20px;			background:url("images/delete.png") no-repeat;		}		a.restore		{			display:inline-block;			width:20px;			height:20px;			background:url("images/restore.png") no-repeat;		}	</style>	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>	<script>	$(function(){		/*$("#table").width($(window).width()-20);		$(window).resize(function(e){			$("#table").width($(window).width()-20);		});*/		$("#dump").click(function(){			$.post("execute.php", { cmd:"dump" }, function(data){				$("#refresh_form").trigger("submit");			});		});		$("#clear_form").on("submit", function(){			if(!confirm("Sei sicuro?"))				return false;		});		$("#table").on("click", function(e){			e.stopPropagation();			e.preventDefault();			var target = $(e.target);			if(target.is("a.filename")) {				target.closest("tr").next().toggle();			} else if(target.is("a.delete")) {				$.post("execute.php", { cmd:"delete-dump", param:target.next().val() }, function(data){					$("#refresh_form").trigger("submit");				});			} else if(target.is("a.restore")) {				$.post("execute.php", { cmd:"restore-dump", param:target.next().val() }, function(data){					var obj = JSON.parse(data);					if(obj.success == 1) {						alert("Dump ripristinato con successo.");					} else {						alert("Errore ripristino dump: " + obj.reason + ".");					}				});			}		});		$("#button_div").on("click", "a[href=#]", function(){			$("#customQueryDiv").slideToggle();			return false;		});		/*$("#executeCustomQueryBtn").on("click", function(){			var query = $("#customQueryArea").val();			if(query.trim() == "")				return false;			$.post("execute.php", { cmd:"execute-query",  param:query }, function(data){				var obj = JSON.parse(data);				if(obj.success == 1) {					alert("Query eseguita con successo");				} else {					alert(obj.reason);				}			});		});		$("#clearCustomQueryBtn").on("click", function(){			$("#customQueryArea").val("");		});*/	});		</script>
</head>
<body>	<div id="button_div">		<div class="logout_div">			<form id="logout_form" action="logout.php" method="post">				<input type="submit" value="Logout"/>							</form>		</div>		<div class="clear_div">			<form id="clear_form" action="svuotaDump.php" method="post">				<input type="submit" value="Svuota"/>							</form>		</div>		<div class="refresh_div">			<form id="refresh_form" action="handleDumps.php" method="post">				<input type="submit" value="Aggiorna"/>							</form>		</div>		<button id="dump">Dump</button>		<a href="admin.php">&dash; Gestione IP &dash;</a>		<!-- <a id="customQuery" href="#">&dash; Query Custom &dash;</a> -->	</div>	<br/>	<!--	<div id="customQueryDiv">		<textarea id="customQueryArea"></textarea><br/>		<button id="executeCustomQueryBtn">Esegui</button>		<button id="clearCustomQueryBtn">Svuota</button>	</div>	-->
	<?php if($dumps->getNDumps() == 0) { ?>	<h3>Nessun Dump</h3>	<?php } else { ?>	<table id="table">		<thead>			<tr>				<th width="80%">Nome file dump</th>				<th width="10%">Applica</th>				<th width="10%">Elimina</th>			</tr>		</thead>		<?php		foreach($dumps->getAllDumps() as $dump)		{			echo "<tr>";			echo "<td>";			echo "<div class='filename_wrapper'>";			echo "<input type='hidden' value='" . $dump['filename'] . "'/>";			echo "<a href='#' class='filename'>" . $dump['filename'] . "</a>";			echo "</div>";			echo "</td>";			echo "<td>";			echo "<div class='center'>";			echo "<a href='#' class='restore'></a>";			echo "<input type='hidden' value='" . $dump['filename'] . "'/>";			echo "</div>";			echo "</td>";			echo "<td>";			echo "<div class='center'>";			echo "<a href='#' class='delete'></a>";			echo "<input type='hidden' value='" . $dump['filename'] . "'/>";			echo "</div>";			echo "</td>";			echo "</tr>";			echo "<tr class='hidden-row'>";			echo "<td colspan='3'>";			echo "<div class='dump_content'><pre>" . $dump['file_content'] . "</pre></div>";			echo "</td>";			echo "</tr>";		}		?>	</table>	<?php } ?>
</body>
</html>